### ISSUE TITLE
Is Heroku SSL add-on required?

### ISSUE THREAD

**Issue by OKNoah** [dmathieu/sabayon#14]
Hi,

I followed the steps in the guide, but SSL does not seem to work. The correct environmental variables seem to have been populated on Heroku. But adding `https://` to my site's URL in the browser shows Heroku's SSL cert, which is a domain mismatch since I'm on my own domain.

Wondering if here is something I'm missing.

**Comment by OKNoah** [comment]
It seems you have to enable `http-si` via `heroku labs:enable http-sin`. Perhaps something to add to the README?

**Comment by dmathieu** [comment]
Yes, this project relies on [Heroku's free SSL](https://blog.heroku.com/archives/2016/5/18/announcing_heroku_free_ssl_beta_and_flexible_dyno_hours) which is currently in public beta.
I'll add a mention of this in the readme.
