### ISSUE TITLE
with force_ssl for rails?

### ISSUE THREAD

**Issue by toobulkeh** [dmathieu/sabayon#18]
If we're using `force_ssl` in a rails application then the first time Sabayon runs it is not able to pick up the HTTP endpoint and fails.

This order-of-operations is a bit of a pain to deal with -- and I'm not sure if force_ssl needs to be turned off each time a new cert is needed.

Ideally, this addon would work with force_ssl since that forces browsers to use secure cookies, among other things.

If that's simply not possible due to the LetsEncrypt specification -- is there a recommended way to handle SSL redirection without `force_ssl` turned on in the Rails application?

Thanks for the help!

**Comment by toobulkeh** [comment]
``` console
--- % heroku run sabayon --remote 
Running sabayon on ⬢ ... up, run.4791
2016/07/12 17:38:16 cert.create email='-email-' domains='[-dns-]'
2016/07/12 17:38:17 [INFO] acme: Registering account for -email-
2016/07/12 17:38:17 [INFO][-dns-] acme: Obtaining bundled SAN certificate
2016/07/12 17:38:17 [INFO][-dns-] acme: Could not find solver for: tls-sni-01
2016/07/12 17:38:17 [INFO][-dns-] acme: Trying to solve HTTP-01
2016/07/12 17:38:17 cert.validate
2016/07/12 17:39:03 cert.validated
2016/07/12 17:39:04 acme: Error 400 - urn:acme:error:tls - Could not connect to http://-dns-/.well-known/acme-chall$
nge/IbQHkJdKbO4BSZHIyVpi5GJR8E7S-6ypRSchoDNK0GY
Error Detail:
        Validation for -dns-:80
        Resolved to:
                -ip-
        Used: -ip-

        Validation for -dns-:443
        Resolved to:
                -ip-
        Used: -ip-
```

**Comment by dmathieu** [comment]
Hey,

I'm afraid there isn't really a solution here. You cannot serve SSL on your domain without having a certificate, so cannot get a certificate with force_ssl.
The only way to resolve this is to not enable force_ssl before you generate the certificate.

Rails' force_ssl will allow you to specify paths where SSL isn't forced too. Doing that on `/.well-known/acme-challenge/*` will also the tool to perform the certificate generation.

**Comment by toobulkeh** [comment]
That makes sense. Any references on how to use the `config.force_ssl` with the custom path in the routes?

Specifically something on a per-environment basis would be preferred.

Thanks!

**Comment by toobulkeh** [comment]
`routes.rb`

``` ruby
  # Let's Encrypt for Sabayon (Heroku)   
  if ENV['ACME_KEY'] && ENV['ACME_TOKEN']   
    get ".well-known/acme-challenge/#{ ENV["ACME_TOKEN"] }" => proc { [200, {}, [ ENV["ACME_KEY"] ] ] }   
  else    
    ENV.each do |var, _|    
      next unless var.start_with?("ACME_TOKEN_")    
      number = var.sub(/ACME_TOKEN_/, '')   
      get ".well-known/acme-challenge/#{ ENV["ACME_TOKEN_#{number}"] }" => proc { [200, {}, [ ENV["ACME_KEY_#{number}"] ] ] }   
    end   
  end
```

**Comment by dmathieu** [comment]
Rails runs force_ssl as a [before_action](https://github.com/rails/rails/blob/1ffa1a852e79feee9d4793fb60992a920909c316/actionpack/lib/action_controller/metal/force_ssl.rb#L65).

So you should be able to do the following:

```
force_ssl :if => proc {|r| !r.match(/^\.well-known\/acme-challenge\//) }
```

Note that I haven't tested this.

**Comment by toobulkeh** [comment]
That's if we used force_ssl as a before_action only -- is there no way to use this with force_ssl the config variable? ([Note the difference of secure cookies](http://www.eq8.eu/blogs/14-config-force_ssl-is-different-than-controller-force_ssl)).

**Comment by dmathieu** [comment]
Another thing you could do is not configure sabayon within your app routes, but use the rack solution.
That way, the token/key page will be served before rails is called, and no force_ssl will come into play.

When using routes, rails' forcing ssl from the app config comes first, and there is no way to override that.
