### ISSUE TITLE
Client times out

### ISSUE THREAD

**Issue by sprice** [dmathieu/sabayon#2]
When I run the `sabayon` command it updates the `ACME_KEY` and `ACME_TOKEN` config vars of my production app, thus restarting it.

Then it tries to validate against the validation URL, but the app is restarting and sabayon times out.

**Comment by dmathieu** [comment]
"times out"? There is no timeout when running one-off dynos (except the 24 hours cycling).
What exact errors are you getting?

**Comment by sprice** [comment]
host could not be reached (since it was restarting). Sorry the exact message is gone from my history.

I updated line 76 of `main.go` to be `time.Sleep(40 * time.Second)` and things are good now

**Comment by sprice** [comment]
To be clear, my production app could not be reached.

**Comment by dmathieu** [comment]
If your app takes longer than 20 seconds to boot, that could indeed cause issues.
Long boot times also means you have downtime every time your app restarts though, which will give you further issues. I think your app's boot time is what should be fixed here.

**Comment by sprice** [comment]
Agreed on needing to boot faster.

That being said I'd also like to use Heroku preboot. I believe this would need to wait ~3-5 minutes for it to work with preboot.

Would you accept a pull request that takes a custom sleep time?

**Comment by dmathieu** [comment]
Sure. When adding it to app.json, could you add a mention about long boot time and the risk of H12s in the description?

**Comment by sprice** [comment]
Sounds good. Time to learn some Go :)

**Comment by apeckham** [comment]
We had this problem today: We used preboot, so env vars take ~3 minutes to update. When Sabayon checked `.well-known/acme-challenge/...` it got a 404. Decided to turn off preboot for now so we can use Sabayon.

**Comment by sprice** [comment]
@apeckham set `RESTART_WAIT_TIME` to `300` (5 mins)
