### ISSUE TITLE
Can a single Sabayon instance update the SSL for multiple Heroku sites?

### ISSUE THREAD

**Issue by vitorbaptista** [dmathieu/sabayon#20]
Sorry if it was asked/answered somewhere else, I couldn't find it. The title basically says it all: can I use a single sabayon to handle multiple SSL certificates?

**Comment by dmathieu** [comment]
You can use a single sabayon instance to handle one site with a single certificate for multiple domains.
But if you have multiple apps, each with a different certificate, you will need one sabayon instance per app.

**Comment by vitorbaptista** [comment]
Thanks for the quick answer (and Sabayon), @dmathieu :beers:

**Comment by bjeanes** [comment]
@dmathieu would you be open to a PR that allowed you to configure multiple apps? E.g. by setting a var like:

```
ACME_APPS="app1:domain1,domain2 app2:domain3"
```

Or is it not worth it given the add-on or Heroku-provided solution alluded to in #26?

**Comment by dmathieu** [comment]
I don't think it's worth it. It'll be adding quite a bit of complexity to this app.
