### ISSUE TITLE
Heroku addon

### ISSUE THREAD

**Issue by edenvicary** [dmathieu/sabayon#26]
I just integrated this for my company successfully. But it takes a little while to configure and you've got to have a whole app environment for each production environment.

Would anyone else be interested in having a similar benefit packaged in a heroku addon?

**Comment by dmathieu** [comment]
Things of the kind are already on their way :wink:

**Comment by vitorbaptista** [comment]
@dmathieu That's great to know! Anywhere I can follow to be notified when the addon is ready?

**Comment by dmathieu** [comment]
I believe there will be something on the heroku blog.

**Comment by ekryski** [comment]
@dmathieu do you have an idea when Heroku might land this? 😁

**Comment by dmathieu** [comment]
Sorry, even if I had an idea I couldn't comment on it.
