### ISSUE TITLE
Including middleware on Rails

### ISSUE THREAD

**Issue by onpaws** [dmathieu/sabayon#32]
Based on this [section](https://github.com/dmathieu/sabayon#rails-apps) of the docs I tried adding
`config.middleware.insert_before 0, SabayonMiddleware`
to application.rb. 

In my case it had to instead be
`config.middleware.insert_before 0, 'SabayonMiddleware'`

If you're interested the relevant Rails source appears to be
`railties-x.x.x/lib/rails/configuration.rb`

I'm not sure what the canonical 'Rails way' is on this but posting in hopes others can benefit.

-----------
Rails 4.1.16
macOS 10.12.1

**Comment by dmathieu** [comment]
That would be because the middleware isn't included yet. A simple `require 'path/to/middleware` at the beginning of the file would have fixed it.
If you wish to open a PR fixing that documentation, I'll gladly merge it though.

**Comment by onpaws** [comment]
Opened a [PR](https://github.com/dmathieu/sabayon/pulls) for this
