### ISSUE TITLE
Running initial Sabayon causes Heroku app to restart (NodeJS/Express)

### ISSUE THREAD

**Issue by SheaBelsky** [dmathieu/sabayon#34]
After configuring the Sabayon app and running it for the first time, it causes the target application to restart itself multiple times. Furthermore, it isn't successfully creating the certificate after validating everything twice. I've followed all the instructions, but I'm trying to figure out why this might not be working.

Whenever I try to enable the SNI lab, it says 
```
! Couldn't find that feature.
```
I believe it's because the feature is now a part of Heroku paid plans. What might be going wrong that's causing the app to restart itself?

I'm using a NodeJS & Express app. I'm also running [KeystoneJS](http://keystonejs.com) as a framework, which might be getting in the way.

**Comment by dmathieu** [comment]
Hi,

Indeed, the lab flag isn't required anymore. I've removed it from the readme.
Yes also, SNI is only available on heroku paid plans. You cannot use this tool if your main app isn't using an heroku paid plan.

You should expect one restart every time sabayon generates/updates certificates, as it needs to set the appropriate config vars.
Multiple restarts are definitely weird. Could you copy/paste the sabayon app logs associated with those restarts?

Thanks

**Comment by SheaBelsky** [comment]
I don't think it's an issue of restarts, but that it appears to be timing out after a certain point in time. My app takes some time to start up, which is a problem moreso on my end than yours. I was able to add the certificate manually, which isn't ideal but I'll try to see if I can reapproach this issue soon.

**Comment by dmathieu** [comment]
You can set the `RESTART_WAIT_TIME` config var on the sabayon app to wait a number of seconds before expecting the app to have restarted.
The default is 20 seconds.

**Comment by dmathieu** [comment]
I'm going to close this issue, as it doesn't seem to be calling for any remediation items on the sabayon codebase.
