### ISSUE TITLE
Error 400 - urn:acme:error:connection - Could not connect to url

### ISSUE THREAD

**Issue by sirius248** [dmathieu/sabayon#38]
I have this issue when use it with a Rails app. Even though I have check all steps carefully, but still don't know what going on. Can you help?

```ruby
2017/01/10 15:30:40 [INFO][www.mydomain.com] The server validated our request
2017/01/10 15:30:40 acme: Error 400 - urn:acme:error:unknownHost - No valid IP addresses found for mydomain.com
Error Detail:
	Validation for mydomain.com:80
	Resolved to:

	Used:
```

**Comment by dmathieu** [comment]
This is definitely not an error with the sabayon source code. It would appear letsencrypt isn't able to access your domain, `mydomain.com` on port 80 to check you are it's owner.
Did you properly configure your domain, and are you able to access it?

**Comment by sirius248** [comment]
Hi @dmathieu, thanks for the quick response. After some crazy hours doing the config with DNS, I finally got it work. Thanks for the great library!

**Comment by dmathieu** [comment]
Awesome! 🌷
