### ISSUE TITLE
Status: 404

### ISSUE THREAD

**Issue by Milan4e** [dmathieu/sabayon#39]
Hi, 

I followed the steps closely and I am getting the following error when trying to run the command manually:

{"id":"not_found","message":"The requested API endpoint was not found. Are you using the right HTTP verb (i.e. `GET` vs. `POST`), and did you specify your intended version with the `Accept` header?"}

Am I doing something wrong here?
Thank you!

**Comment by dmathieu** [comment]
Do you have the `ssl` add-on on that app by any chance?

**Comment by Milan4e** [comment]
Thanks for your reply!
I had. I removed it and changed DNS records but its still the same error. Maybe it needs some time because of the DNS change. I will try later or tomorrow and comment here on the outcome.

**Comment by dmathieu** [comment]
Thanks. There was no related changes in the Heroku API recently, and I just tried on my own sabayon installation successfully.

**Comment by Milan4e** [comment]
Unfortunately its still not working. I did not mention that I am using KOA framework so maybe thats the problem. The http://appname.herokuapp.com/.well-known/acme-challenge/:token endpoint is working fine.

**Comment by Milan4e** [comment]
Would you suggest something else for me to try? Much appreciated! Thanks!

**Comment by dmathieu** [comment]
Would you be able to have it work with the same sabayon app but to create a certificate on a test app using only one of the examples provided in the README?

**Comment by Milan4e** [comment]
Sorry for the delay on this. I created new dynos and configured it from scratch and it worked. So it was not an issue with the framework. This works on KOA just fine. Thanks for your help and for this neat tool!
