### ISSUE TITLE
Some clients that work with other letsencypt sites not working

### ISSUE THREAD

**Issue by sprice** [dmathieu/sabayon#4]
After happily testing my secured app in Chrome on OSX the last day or two I've tested some other browsers and discovered it fails in Firefox OSX and Chrome Android (Your connection is not secure).

After running my domain through ssllabs.com I noticed an [issue](https://www.ssllabs.com/ssltest/analyze.html?d=www.hellodial.co&latest): "Chain issues: incomplete" For path #2, it lists an extra download, whereas when [checking](https://www.ssllabs.com/ssltest/analyze.html?viaform=on&d=helloworld.letsencrypt.org) `helloworld.letsencrypt.org`, path #2 is listed as "sent by server"

Another issue I've noticed is that running `$ openssl s_client -connect hellodial.co:443` results in [the following failure](https://gist.github.com/sprice/921bcd5eced7c634bc09abdcf9fcbd05) yet this works for `helloworld.letsencrypt.org`

**Comment by rdoh** [comment]
I was about to raise this same issue myself. I have used sabayon for https://letters.solarcitizens.org.au, and see the same problem, although I only get a warning on Android. Neither Firefox 33 nor 46 (on OSX 10.11.5) display a warning for me.  

I have checked the example mentioned on @dmathieu's blog -- codetriage.com -- with ssllabs.com and that seems to have the same issue.

I haven't had a look at the code yet, but perhaps it is not uploading the `chain.pem` (which should be generated by the letsencrypt client)?

PS. Thanks @dmathieu for your work on this. It was really smooth to use (aside from this issue!).

**Comment by sprice** [comment]
I just updated my cert using `sudo letsencrypt certonly --manual` and `heroku _certs:update` and things are looking better. All the browsers I test are working, I get an A rating on ssllabs.com and the nodejs request library is happy hitting my server, but the `openssl` command above still fails (that i'm not to worried about).

I'll take a look at the sabayon code and see what might be the issue. (edit: not familiar enough with golang or heroku api to make sense of this right now 😄 )

**Comment by dmathieu** [comment]
Could you try generating your certificates from #5 and see if that solves the issue?

**Comment by sprice** [comment]
success! This is so great, thanks.

**Comment by dmathieu** [comment]
Awesome, thanks. Bringing that PR in and closing this issue.
Thank you both for reporting this. 💖
