### ISSUE TITLE
Asynchronous/Parallel  Domain Authentication?

### ISSUE THREAD

**Issue by danielflippance** [dmathieu/sabayon#40]
It seems to be the case that the process to authenticate all the domains listed in ACME_DOMAIN is a synchronous process (although I'm not certain because I'm very new to the GO language).

When the scheduler runs from Heroku, it seems to authenticate the domains in a synchronous and serial manner which means the more domains I add, the longer it takes to get a new cert.

Is this correct? If so, is there a way to make it asynchronous and parallel so that the number of domains doesn't really affect the time it takes to get a cert?

**Comment by dmathieu** [comment]
I have no plans for improvements/refactorings on sabayon. It will be deprecated soon.
