### ISSUE TITLE
ACME DNS challenge

### ISSUE THREAD

**Issue by Mojo90** [dmathieu/sabayon#41]
Are there any plans to also integrate the possibility of the [DNS](https://github.com/ietf-wg-acme/acme/blob/master/draft-ietf-acme-acme.md#dns) challenge and integrate this with e.g. Cloudflare? 
The advantage would be that the application code must not be changed.

**Comment by dmathieu** [comment]
Hi,
I have no plans for any improvements on sabayon. It will be deprecated soon.

**Comment by Mojo90** [comment]
Ok got it.
So if this plugin is deprecated, Heroku will support Let's encrypt natively? Are there any information published yet?
