### ISSUE TITLE
Problems with redirect to https

### ISSUE THREAD

**Issue by funkenstrahlen** [dmathieu/sabayon#46]
I use express and redirect users to https by default:

```javascript
var forceSSL = function (req, res, next) {
  if (req.headers['x-forwarded-proto'] !== 'https') {
      return res.redirect(['https://', req.get('Host'), req.url].join(''));
  }
  return next();
};
app.use(forceSSL);  
```

This lets the domain authentication fail as letsencrypt connects via http. I disabled this redirect for the first certificate generation. Now it is enabled again.

**Will this also cause problems when I try to renew my certificate?**

**Comment by dmathieu** [comment]
Hey,

Yes, this will cause problems when you try to renew your certificate, as letsencrypt needs to make a request to your app.
You need to ignore the redirect if the path matches the letsencrypt URI.

**Comment by funkenstrahlen** [comment]
Thank you for your quick response. Got it working now using your suggestion.
