### ISSUE TITLE
Add an alternate method to set Token & Key on main app

### ISSUE THREAD

**Issue by prognostikos** [dmathieu/sabayon#47]
Just testing Sabayon on one of our apps and it works like a charm. Thanks!

In our case, as we're using `preboot` on our dynos, we have to wait circa 3 minutes in between each dyno restart during the domain validation step. As Sabayon seems to add each token & key for multiple domains in serial, this can end up taking a long time with even a modest list of domains.

Would you be interested in a PR for an option where instead of setting config vars on the main app we POST to an endpoint on the main app with the domain, token & key (leaving it up to the main app as to how it should store the result and reply to the challenge?)

Alternatively, I guess we could set all of the configuration variables at once, so there's only one restart no matter now many domains are in ACME_DOMAIN?

**Comment by dmathieu** [comment]
Hi,
Sorry, I'm not in favor of making any substential changes to sabayon. I cannot say more about it, but it will be deprecated soon.

**Comment by prognostikos** [comment]
Fair enough @dmathieu. Would you accept a PR that sets all of the config vars in one go, rather than  once per domain?

I hope that what you can't say more about is native Heroku support for LE :)

**Comment by dmathieu** [comment]
Yes, I would accept a PR which sets all config vars in one go.
But unfortunately, it would require a kind of overhaul of the app.
