### ISSUE TITLE
rewrite rule for nginx and php

### ISSUE THREAD

**Issue by ivoba** [dmathieu/sabayon#48]
im sorry, i am not able to get the redirect right for php and nginx, maybe you can help me.

i tried with:
```

location ~ ^/.well-known/acme-challenge/(.*)$ {
    if (!-e $request_filename){
      rewrite ^(.*)$ /.well-known/acme-challenge/index.php?q=$1 last;
      break;
    }
}

location ~ \.php$ {
    try_files @heroku-fcgi @heroku-fcgi;
}
```
but this results in a downloaded file, so guess the redirect is fine but its not interpreted as php file.

**Comment by onpaws** [comment]
I'm speculating, but browsers usually look at HTTP headers and MIME types when deciding whether to render/display or download a resource.

I suggest verifying those two pieces.

**Comment by dmathieu** [comment]
This is definitely a content-type issue.
Try adding the following right after your `rewrite` call:

```
add_header Content-Type text/plain;
```

**Comment by ivoba** [comment]
the downloaded file contains PHP script, so i assume its not interpreted as php file from nginx.
i doubt that the content-type will help here.

**Comment by dmathieu** [comment]
In any case, this is an nginx issue, not one with sabayon.
My recommendation would be to open a question on stackoverflow.
