### ISSUE TITLE
Automatic Rails generation

### ISSUE THREAD

**Issue by dijonkitchen** [dmathieu/sabayon#50]
Is it easier to use this gem for Rails applications (or all Heroku if possible) and then just run it every 2 months automatically? I can't tell if it's simpler than sabayon's implementation and setup. 

https://github.com/KMarshland/heroku-ssl

**Comment by dmathieu** [comment]
I haven't tried that gem, so cannot say.
Though my personal opinion is that mixing certificate generation with your main app is a bad idea.

But you're free to pick any solution you want.
