### ISSUE TITLE
Wrapping the Rack middleware in a gem

### ISSUE THREAD

**Issue by pat** [dmathieu/sabayon#51]
Firstly, I realise this has been done before (as noted in #25), though I wasn't aware of that when I began.

My approach is simpler - it's really just the middleware, and there's no dependency on Rails. It also should perform a bit better, because it caches the available ACME key/token pairs, rather than finding them from environment variables on every request.
https://github.com/pat/sabayon_middleware

This is offered purely as an alternative to what you've documented in your README. If you think it's useful for others, feel free to mention it there. If you think it is simple enough as a replacement for your middleware, that's great too. If neither of those are the case, no worries :) I've found it's useful for me, and I figure at least logging it here may help others come across it.

Also: thanks for the work on Sabayon, it's pretty neat!

**Comment by dmathieu** [comment]
Thanks. I'd rather not ask people to add an additional external dependency on their app.

**Comment by dmathieu** [comment]
Also, https://blog.heroku.com/announcing-automated-certificate-management
