### ISSUE TITLE
Supporting SSL Endpoint certificates?

### ISSUE THREAD

**Issue by pat** [dmathieu/sabayon#52]
Hi @dmathieu. Would you be open to supporting Heroku's legacy SSL Endpoint certificates?

The Heroku API has endpoints for this purpose, and I'm happy to at least attempt a pull request (though my Go skills are almost non-existent). I have one app that's still on the old endpoint, and while I'd love to migrate it, it actually is the main API for a Heroku Add-on, and thus I have customers using old versions of Ruby that annoyingly don't play nicely with the SNI approach.

Just pondering whether it's worth my effort to understand enough of the Go code to make a contribution, and whether it would be merged (if I have to maintain a fork myself, it's probably a better use of my time to just pay the yearly fee for a non-letsencrypt certificate).

**Comment by dmathieu** [comment]
Nope. This lib is not receiving any changes anymore.
Also, why would you want to use the SSL endpoint certificates? They cost $20/month, and will be entirely removed at some point.

Also, https://blog.heroku.com/announcing-automated-certificate-management
