### ISSUE TITLE
Error when domain env includes a space around domain name

### ISSUE THREAD

**Issue by stefan-kolb** [dmathieu/sabayon#6]
e.g., `paasify.it,  www.paasify.it`

results in 

``` sh
2016/06/03 12:24:08 [INFO][paasify.it,  www.paasify.it] acme: Obtaining bundled SAN certificate
2016/06/03 12:24:08 acme: Error 400 - urn:acme:error:malformed - Error creating new authz :: Invalid character in DNS name
```

Can we just auto strip this inside sabayon?

**Comment by dmathieu** [comment]
Yes, we split domain names expecting comas without spaces: https://github.com/dmathieu/sabayon/blob/master/cmd/sabayon/main.go#L23
I'd be willing for a documentation (and/or addition to the description in app.json), but I don't think actually supporting both formats is worth it.

**Comment by stefan-kolb** [comment]
The error message was just not immediately intuitive for me when this error occured. This problem might occur more often, as by times you just add a space after a comma. What about just using `strings.TrimSpace(s)` on the resulting array? Either way, I'm fine with any of your decisions, I just wanted to bring up this problem I had in the workflow.

**Comment by dmathieu** [comment]
TrimSpace can't be used on the resulting array.
We have to loop through all entries, which isn't so problematic itself of course. But I see your point of adding config vars without rereading the content of app.json.

:+1: to loop through the array and trim the space on all entries. Feel free to open a PR doing so, or let me know and I can do it myself.

**Comment by stefan-kolb** [comment]
Of course I meant looping the array and using TrimSpace :wink: Will try to do a PR, wanted to try out Go anyway :smile:
